# fly.toml app configuration file generated for gsan on 2024-08-11T17:49:48-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gsan'
primary_region = 'mia'

[build]

[env]
  HYPERDX_ENABLE_ADVANCED_NETWORK_CAPTURE = '1'
  OTEL_SERVICE_NAME = 'gsan-prod'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
