# fly.toml app configuration file generated for gsan on 2024-03-09T21:13:00-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gsan'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[env]
  OTEL_SERVICE_NAME = "gsan-prod"
  HYPERDX_ENABLE_ADVANCED_NETWORK_CAPTURE = 1

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
